Use a consistent response syntax for 2 of 4 of the endpoints WA-160
broadinstitute/martha pull request #155
Opened 2020-05-10 01:16 UTC by kshakir

2020-05-11 22:06 UTC, salonishah11 requested changes
Can you also please update the Martha v3 section in README  with the new response schema for `martha_v3` and the support for DRS v1.0 only going forward?

2020-05-12 16:00 UTC, rsasch requested changes
You added documentation for the martha_v3 endpoint, but it also looks like you changed the structure of the response for the fileSummaryV1 endpoint, too?  If so, please update the docs for that, as well.

2020-05-12 16:00 UTC, rsasch commented on README.md
> +`https://[hostname]/ga4gh/drs/v1/object/[path]`, and then return DRS v1.0 compatible json metadata.
nit: JSON is in all-caps in the text above, please make consistent

2020-05-12 16:00 UTC, rsasch commented on README.md
> +not yet been upgraded to support the DRS request path-prefix and DRS response json metadata, so `martha_v2` still
see nit for line 62

2020-05-12 17:48 UTC, rsasch commented on README.md
> + googleServiceAccount: string, [always null]
my bad, you added it 👍

2020-05-12 20:27 UTC, salonishah11 approved these changes
LGTM 👍

2020-05-13 16:04 UTC, rsasch approved these changes

2020-05-13 16:05 UTC, merged